baseURL2 = "http://localhost:1313/learning/"
baseURL = "http://polodev.github.io/learning/"
languageCode = "en-us"
publishDir="docs"
title = "Learning 101"
Paginate=2
[taxonomy]
  category="categories"
  tag="tags"
[outputs]
home = [ "HTML", "RSS", "JSON"]
